version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
      timezone: America/New_York
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
      timezone: America/New_York
    open-pull-requests-limit: 99
